---
- hosts: all
  become: yes

  vars:
    haproxy_major_version: "2.0"
    haproxy_version: "2.0.12"
    haproxy_url: "https://www.haproxy.org/download/{{ haproxy_major_version }}/src/haproxy-{{ haproxy_version }}.tar.gz"
    haproxy_doc: http://www.haproxy.org/download/{{ haproxy_major_version }}/doc/configuration.txt.gz

  tasks:

  - name: Install prereqs package
    yum:
      name:
        - make
        - gcc
        - perl
        - pcre-static
        - pcre-devel
        - zlib-devel
        - lua
        - lua-devel
        - openssl
        - openssl-devel
      state: present

  - name: Enable IP forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes

  - name: Enable binding to non-local IP addresses
    sysctl:
      name: net.ipv4.ip_nonlocal_bind
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes

  - name: Download and extract sources
    unarchive:
      src: "{{ haproxy_url }}"
      dest: /tmp
      remote_src: yes

  - name: Compilation
    shell: |
       cd /tmp/haproxy-{{ haproxy_version }}
       make -j $(nproc) TARGET=linux-glibc USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_CRYPT_H=1 USE_LIBCRYPT=1

  - name: Installation
    shell: |
       cd /tmp/haproxy-{{ haproxy_version }}
       make install

  - name: create haproxy user
    user:
      name: haproxy
      system: yes

  - name: Create haproxy directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /etc/haproxy
      - /var/lib/haproxy
      - /usr/share/doc/haproxy

  - name: Init haproxy files
    file:
      path: "{{ item }}"
      state: touch
    with_items:
      - /var/lib/haproxy/stats
      - /etc/default/haproxy

  - name: check previous haproxy configuration
    stat:
      path: /etc/haproxy/haproxy.cfg
    register: stat_result

  - name: upload default haproxy configuration
    copy:
      src: resources/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
    when: stat_result.stat.exists|bool == false

  - name: Download documentation
    get_url:
      url: "{{ haproxy_doc }}"
      dest: /usr/share/doc/haproxy/configuration.txt.gz

  - name: Create a symbolic link to /usr/sbin/haproxy
    file:
      src: /usr/local/sbin/haproxy
      dest: /usr/sbin/haproxy
      state: link

  - name: create haproxy service
    copy:
      src: resources/haproxy.service
      dest: /etc/systemd/system/haproxy.service

  - name: enable haproxy service
    service:
      name: haproxy
      enabled: yes

  - name: start haproxy service
    service:
      name: haproxy
      state: started

  - name: Remove temporary directory
    file:
      path: /tmp/haproxy-{{ haproxy_version }}
      state: absent